INFO 2024-03-07 11:46:43,049 autoreload 6804 3288 Watching for file changes with StatReloader
DEBUG 2024-03-07 11:46:45,695 views 6804 3440 <WSGIRequest: GET '/'>
INFO 2024-03-07 11:46:45,712 basehttp 6804 3440 "GET / HTTP/1.1" 200 226
DEBUG 2024-03-07 11:46:47,908 views 6804 3440 <WSGIRequest: GET '/about/'>
INFO 2024-03-07 11:46:47,910 basehttp 6804 3440 "GET /about/ HTTP/1.1" 200 8
DEBUG 2024-03-07 11:46:53,718 views 6804 3440 <WSGIRequest: GET '/about/'>
INFO 2024-03-07 11:46:53,719 basehttp 6804 3440 "GET /about/ HTTP/1.1" 200 8
INFO 2024-03-11 14:43:26,921 autoreload 8048 14420 Watching for file changes with StatReloader
DEBUG 2024-03-11 14:43:34,466 views 8048 316 <WSGIRequest: GET '/'>
INFO 2024-03-11 14:43:34,494 basehttp 8048 316 "GET / HTTP/1.1" 200 226
WARNING 2024-03-11 14:43:39,056 log 8048 316 Not Found: /favicon.ico
WARNING 2024-03-11 14:43:39,133 basehttp 8048 316 "GET /favicon.ico HTTP/1.1" 404 3429
INFO 2024-03-13 11:12:47,012 autoreload 21812 7576 Watching for file changes with StatReloader
DEBUG 2024-03-13 11:13:11,550 views 21812 23040 <WSGIRequest: GET '/'>
INFO 2024-03-13 11:13:11,609 basehttp 21812 23040 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 11:13:14,848 log 21812 4408 Not Found: /favicon.ico
WARNING 2024-03-13 11:13:14,916 basehttp 21812 4408 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 11:13:49,358 views 21812 19944 <WSGIRequest: GET '/about/'>
INFO 2024-03-13 11:13:49,360 basehttp 21812 19944 "GET /about/ HTTP/1.1" 200 8
DEBUG 2024-03-13 11:15:38,145 views 21812 5144 <WSGIRequest: GET '/'>
INFO 2024-03-13 11:15:38,175 basehttp 21812 5144 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 11:15:38,880 log 21812 5144 Not Found: /favicon.ico
WARNING 2024-03-13 11:15:38,926 basehttp 21812 5144 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 11:15:43,815 views 21812 13104 <WSGIRequest: GET '/about/'>
INFO 2024-03-13 11:15:43,817 basehttp 21812 13104 "GET /about/ HTTP/1.1" 200 8
INFO 2024-03-13 11:16:56,462 autoreload 21812 7576 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py changed, reloading.
INFO 2024-03-13 11:16:58,814 autoreload 14148 10936 Watching for file changes with StatReloader
DEBUG 2024-03-13 11:17:01,289 views 14148 6064 <WSGIRequest: GET '/'>
INFO 2024-03-13 11:17:01,577 basehttp 14148 6064 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 11:17:02,355 log 14148 6064 Not Found: /favicon.ico
WARNING 2024-03-13 11:17:02,578 basehttp 14148 6064 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 11:17:03,950 views 14148 6064 <WSGIRequest: GET '/about/'>
INFO 2024-03-13 11:17:03,954 basehttp 14148 6064 "GET /about/ HTTP/1.1" 200 227
DEBUG 2024-03-13 11:17:07,407 views 14148 6064 <WSGIRequest: GET '/about/'>
INFO 2024-03-13 11:17:07,409 basehttp 14148 6064 "GET /about/ HTTP/1.1" 200 227
INFO 2024-03-13 11:18:22,240 autoreload 14148 10936 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py changed, reloading.
INFO 2024-03-13 11:18:29,554 autoreload 22968 19888 Watching for file changes with StatReloader
DEBUG 2024-03-13 11:18:39,045 views 22968 22384 <WSGIRequest: GET '/'>
INFO 2024-03-13 11:18:39,135 basehttp 22968 22384 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 11:18:39,903 log 22968 22384 Not Found: /favicon.ico
WARNING 2024-03-13 11:18:39,947 basehttp 22968 22384 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 11:18:41,357 views 22968 22384 <WSGIRequest: GET '/about/'>
INFO 2024-03-13 11:18:41,360 basehttp 22968 22384 "GET /about/ HTTP/1.1" 200 221
INFO 2024-03-13 12:30:45,505 autoreload 17392 15824 Watching for file changes with StatReloader
DEBUG 2024-03-13 12:33:46,986 views 22968 13964 <WSGIRequest: GET '/'>
INFO 2024-03-13 12:33:47,374 basehttp 22968 13964 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 12:33:48,499 log 22968 13964 Not Found: /favicon.ico
WARNING 2024-03-13 12:33:48,759 basehttp 22968 13964 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 12:34:02,660 views 22968 15912 tail
ERROR 2024-03-13 12:34:04,051 log 22968 15912 Internal Server Error: /coin/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py", line 29, in coin
    return render(request, 'coin.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: coin.html
ERROR 2024-03-13 12:34:04,151 basehttp 22968 15912 "GET /coin/ HTTP/1.1" 500 81115
INFO 2024-03-13 12:35:56,401 autoreload 1248 23080 Watching for file changes with StatReloader
ERROR 2024-03-13 12:36:01,299 exception 22968 20644 Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2024-03-13 12:36:01,447 log 22968 20644 Bad Request: /
WARNING 2024-03-13 12:36:01,453 basehttp 22968 20644 "GET / HTTP/1.1" 400 69515
ERROR 2024-03-13 12:36:02,131 exception 22968 14720 Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'localhost:8000'. You may need to add 'localhost' to ALLOWED_HOSTS.
WARNING 2024-03-13 12:36:02,209 log 22968 14720 Bad Request: /favicon.ico
WARNING 2024-03-13 12:36:02,211 basehttp 22968 14720 "GET /favicon.ico HTTP/1.1" 400 69357
INFO 2024-03-13 12:42:47,388 autoreload 23516 14196 Watching for file changes with StatReloader
DEBUG 2024-03-13 12:42:51,402 views 23516 1004 <WSGIRequest: GET '/'>
INFO 2024-03-13 12:42:51,432 basehttp 23516 1004 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 12:42:55,525 log 23516 1004 Not Found: /favicon.ico
WARNING 2024-03-13 12:42:55,612 basehttp 23516 1004 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 12:43:00,343 views 23516 1004 head
ERROR 2024-03-13 12:43:00,679 log 23516 1004 Internal Server Error: /coin/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py", line 29, in coin
    return render(request, 'coin.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: coin.html
ERROR 2024-03-13 12:43:00,694 basehttp 23516 1004 "GET /coin/ HTTP/1.1" 500 81289
INFO 2024-03-13 12:45:05,198 autoreload 23516 14196 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py changed, reloading.
INFO 2024-03-13 12:45:08,980 autoreload 348 15812 Watching for file changes with StatReloader
DEBUG 2024-03-13 12:45:19,684 views 348 10932 <WSGIRequest: GET '/'>
INFO 2024-03-13 12:45:19,708 basehttp 348 10932 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 12:45:21,027 log 348 10932 Not Found: /favicon.ico
WARNING 2024-03-13 12:45:21,097 basehttp 348 10932 "GET /favicon.ico HTTP/1.1" 404 3429
DEBUG 2024-03-13 12:45:26,264 views 348 10932 tail
INFO 2024-03-13 12:45:26,290 basehttp 348 10932 "GET /coin/ HTTP/1.1" 200 224
DEBUG 2024-03-13 12:45:29,449 views 348 10932 tail
INFO 2024-03-13 12:45:29,476 basehttp 348 10932 "GET /coin/ HTTP/1.1" 200 224
DEBUG 2024-03-13 12:45:32,393 views 348 10932 tail
INFO 2024-03-13 12:45:32,440 basehttp 348 10932 "GET /coin/ HTTP/1.1" 200 224
INFO 2024-03-13 12:51:37,117 autoreload 348 15812 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\urls.py changed, reloading.
INFO 2024-03-13 12:51:40,033 autoreload 16464 6140 Watching for file changes with StatReloader
INFO 2024-03-13 13:05:37,625 autoreload 6444 23500 Watching for file changes with StatReloader
INFO 2024-03-13 13:10:49,117 autoreload 6444 23500 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py changed, reloading.
INFO 2024-03-13 13:10:53,295 autoreload 23236 21936 Watching for file changes with StatReloader
INFO 2024-03-13 13:14:08,952 autoreload 11988 13392 Watching for file changes with StatReloader
INFO 2024-03-13 13:14:48,324 autoreload 15548 9000 Watching for file changes with StatReloader
DEBUG 2024-03-13 13:14:51,122 views 15548 15040 <WSGIRequest: GET '/'>
INFO 2024-03-13 13:14:51,503 basehttp 15548 15040 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 13:14:53,864 log 15548 15040 Not Found: /favicon.ico
WARNING 2024-03-13 13:14:54,232 basehttp 15548 15040 "GET /favicon.ico HTTP/1.1" 404 3479
INFO 2024-03-13 13:14:58,823 basehttp 15548 15040 "GET /coin/2 HTTP/1.1" 301 0
DEBUG 2024-03-13 13:14:58,838 views 15548 9744 head
ERROR 2024-03-13 13:14:59,103 log 15548 9744 Internal Server Error: /coin/2/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp\views.py", line 30, in coin
    return render(request, 'myapp/coin.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\urls\resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'coin' with no arguments not found. 1 pattern(s) tried: ['coin/(?P<amount_flips>[0-9]+)/\\Z']
ERROR 2024-03-13 13:14:59,154 basehttp 15548 9744 "GET /coin/2/ HTTP/1.1" 500 149452
INFO 2024-03-13 13:16:20,934 autoreload 10492 22836 Watching for file changes with StatReloader
DEBUG 2024-03-13 13:16:23,672 views 10492 6140 <WSGIRequest: GET '/'>
INFO 2024-03-13 13:16:23,919 basehttp 10492 6140 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 13:16:24,624 log 10492 6140 Not Found: /favicon.ico
WARNING 2024-03-13 13:16:24,768 basehttp 10492 6140 "GET /favicon.ico HTTP/1.1" 404 3479
DEBUG 2024-03-13 13:16:35,340 views 10492 6140 head
INFO 2024-03-13 13:16:35,342 basehttp 10492 6140 "GET /coin/2/ HTTP/1.1" 200 350
INFO 2024-03-13 14:57:48,494 autoreload 20192 16508 Watching for file changes with StatReloader
INFO 2024-03-13 14:58:26,511 autoreload 20192 16508 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 14:58:28,340 autoreload 7744 5628 Watching for file changes with StatReloader
INFO 2024-03-13 14:59:53,633 autoreload 15372 15316 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:00:03,194 views 15372 17812 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:00:03,403 basehttp 15372 17812 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 15:00:05,104 log 15372 17812 Not Found: /favicon.ico
WARNING 2024-03-13 15:00:05,458 basehttp 15372 17812 "GET /favicon.ico HTTP/1.1" 404 4298
WARNING 2024-03-13 15:00:14,252 log 15372 8824 Not Found: /client/2/week
WARNING 2024-03-13 15:00:14,254 basehttp 15372 8824 "GET /client/2/week HTTP/1.1" 404 4304
INFO 2024-03-13 15:00:39,758 basehttp 15372 12484 "GET /orders/2/week HTTP/1.1" 301 0
INFO 2024-03-13 15:00:39,806 basehttp 15372 17360 "GET /orders/2/week/ HTTP/1.1" 200 641
INFO 2024-03-13 15:04:50,247 autoreload 15372 15316 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:04:56,009 autoreload 22068 7780 Watching for file changes with StatReloader
INFO 2024-03-13 15:07:59,015 autoreload 22068 7780 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:08:03,352 autoreload 21536 23436 Watching for file changes with StatReloader
INFO 2024-03-13 15:08:36,072 autoreload 21536 23436 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:08:38,533 autoreload 18428 17416 Watching for file changes with StatReloader
INFO 2024-03-13 15:09:24,019 autoreload 18428 17416 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:09:26,892 autoreload 9232 22868 Watching for file changes with StatReloader
INFO 2024-03-13 15:10:17,006 autoreload 9232 22868 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:10:20,373 autoreload 21036 23528 Watching for file changes with StatReloader
INFO 2024-03-13 15:12:16,592 autoreload 21036 23528 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:12:18,555 autoreload 6472 6484 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:12:23,497 views 6472 14492 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:12:23,818 basehttp 6472 14492 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 15:12:24,793 log 6472 14492 Not Found: /favicon.ico
WARNING 2024-03-13 15:12:24,956 basehttp 6472 14492 "GET /favicon.ico HTTP/1.1" 404 4298
ERROR 2024-03-13 15:12:30,782 log 6472 3336 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 18, in orders_week
    orders.sort(key=lambda: order.date_ordered,reverse=True)
    ^^^^^^^^^^^
AttributeError: 'QuerySet' object has no attribute 'sort'
ERROR 2024-03-13 15:12:30,845 basehttp 6472 3336 "GET /orders/2/week/ HTTP/1.1" 500 66739
INFO 2024-03-13 15:16:38,456 autoreload 6472 6484 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:16:40,041 autoreload 12892 9888 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:16:42,401 views 12892 5328 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:16:42,592 basehttp 12892 5328 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 15:16:43,326 log 12892 5328 Not Found: /favicon.ico
WARNING 2024-03-13 15:16:43,436 basehttp 12892 5328 "GET /favicon.ico HTTP/1.1" 404 4298
ERROR 2024-03-13 15:16:49,752 log 12892 20688 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 17, in orders_week
    orders = Order.objects.filter(client=client).order_by('-date')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 1701, in order_by
    obj.query.add_ordering(*field_names)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\query.py", line 2253, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date' into field. Choices are: client, client_id, date_ordered, id, products, total_price
ERROR 2024-03-13 15:16:49,762 basehttp 12892 20688 "GET /orders/2/week/ HTTP/1.1" 500 82329
INFO 2024-03-13 15:17:22,340 autoreload 12892 9888 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:17:24,100 autoreload 7232 19988 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:17:26,293 views 7232 17760 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:17:26,486 basehttp 7232 17760 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:17:34,232 log 7232 22184 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    date_diff =datetime.timedelta(order.date_ordered - datetime.now()).days
               ^^^^^^^^^^^^^^^^^^
AttributeError: type object 'datetime.datetime' has no attribute 'timedelta'
ERROR 2024-03-13 15:17:34,246 basehttp 7232 22184 "GET /orders/2/week/ HTTP/1.1" 500 67280
INFO 2024-03-13 15:18:08,920 autoreload 7232 19988 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:18:10,606 autoreload 12592 15812 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:18:19,907 views 12592 11352 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:18:20,025 basehttp 12592 11352 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:18:25,889 log 12592 11352 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    date_diff = timedelta(order.date_ordered - datetime.now()).days
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:18:25,894 basehttp 12592 11352 "GET /orders/2/week/ HTTP/1.1" 500 67206
INFO 2024-03-13 15:19:55,893 autoreload 12592 15812 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:19:58,082 autoreload 10244 15288 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:20:00,646 views 10244 20108 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:20:00,689 basehttp 10244 20108 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:20:08,996 log 10244 20108 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 22, in orders_week
    date_diff = timedelta(order.date_ordered - datetime.now()).days
                          ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:20:09,001 basehttp 10244 20108 "GET /orders/2/week/ HTTP/1.1" 500 67200
INFO 2024-03-13 15:20:56,059 autoreload 10244 15288 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:20:59,140 autoreload 5480 5176 Watching for file changes with StatReloader
INFO 2024-03-13 15:21:40,526 autoreload 5480 5176 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:21:42,279 autoreload 22516 3288 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:21:44,298 views 22516 2008 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:21:44,385 basehttp 22516 2008 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:21:49,771 log 22516 2008 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    date_diff = (order.date_ordered - datetime.now()).days
                 ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:21:49,787 basehttp 22516 2008 "GET /orders/2/week/ HTTP/1.1" 500 67170
INFO 2024-03-13 15:22:15,392 autoreload 22516 3288 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:22:17,743 autoreload 10772 16544 Watching for file changes with StatReloader
INFO 2024-03-13 15:22:53,834 autoreload 10772 16544 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:22:55,552 autoreload 8424 15080 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:22:57,098 views 8424 12816 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:22:57,247 basehttp 8424 12816 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:23:03,167 log 8424 21460 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    date_diff = timedelta(datetime.now() - order.date_ordered).days
                          ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:23:03,173 basehttp 8424 21460 "GET /orders/2/week/ HTTP/1.1" 500 67206
INFO 2024-03-13 15:24:06,604 autoreload 8424 15080 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:24:08,939 autoreload 18736 18036 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:24:10,805 views 18736 12900 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:24:10,860 basehttp 18736 12900 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:24:17,651 log 18736 12900 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    date_diff = datetime.now() - order.date_ordered
                ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:24:17,656 basehttp 18736 12900 "GET /orders/2/week/ HTTP/1.1" 500 67133
INFO 2024-03-13 15:25:38,606 autoreload 18736 18036 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:25:40,238 autoreload 2268 19628 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:25:42,974 views 2268 224 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:25:42,994 basehttp 2268 224 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:25:49,110 log 2268 224 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    date_diff = datetime.utcnow() - order.date_ordered
                ~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:25:49,114 basehttp 2268 224 "GET /orders/2/week/ HTTP/1.1" 500 67145
INFO 2024-03-13 15:26:37,182 autoreload 2268 19628 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:26:39,469 autoreload 22992 11496 Watching for file changes with StatReloader
INFO 2024-03-13 15:29:26,856 autoreload 22992 11496 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:29:31,453 autoreload 9484 15708 Watching for file changes with StatReloader
INFO 2024-03-13 15:31:19,174 autoreload 9484 15708 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:31:21,050 autoreload 22100 15092 Watching for file changes with StatReloader
ERROR 2024-03-13 15:31:26,678 log 22100 21984 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 21, in orders_week
    new_date.replace(tzinfo=timezone)
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'function'
ERROR 2024-03-13 15:31:26,691 basehttp 22100 21984 "GET /orders/2/week/ HTTP/1.1" 500 67600
INFO 2024-03-13 15:32:53,185 autoreload 22100 15092 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:32:55,315 autoreload 14288 14768 Watching for file changes with StatReloader
ERROR 2024-03-13 15:32:58,984 log 14288 9672 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 22, in orders_week
    new_date2.replace(tzinfo=timezone)
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'function'
ERROR 2024-03-13 15:32:59,006 basehttp 14288 9672 "GET /orders/2/week/ HTTP/1.1" 500 67795
INFO 2024-03-13 15:33:16,369 autoreload 14288 14768 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:33:17,921 autoreload 18780 3164 Watching for file changes with StatReloader
ERROR 2024-03-13 15:33:22,525 log 18780 13832 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 23, in orders_week
    date_diff = new_date2 - new_date1
                ~~~~~~~~~~^~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:33:22,542 basehttp 18780 13832 "GET /orders/2/week/ HTTP/1.1" 500 67683
INFO 2024-03-13 15:35:05,759 autoreload 18780 3164 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:35:08,903 autoreload 16000 23504 Watching for file changes with StatReloader
ERROR 2024-03-13 15:35:12,457 log 16000 5328 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 22, in orders_week
    new_date1 = new_date1.replace(tzinfo=timezone)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'function'
ERROR 2024-03-13 15:35:12,470 basehttp 16000 5328 "GET /orders/2/week/ HTTP/1.1" 500 67843
ERROR 2024-03-13 15:35:17,910 log 16000 4512 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 22, in orders_week
    new_date1 = new_date1.replace(tzinfo=timezone)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'function'
ERROR 2024-03-13 15:35:17,919 basehttp 16000 4512 "GET /orders/2/week/ HTTP/1.1" 500 67843
INFO 2024-03-13 15:36:04,890 autoreload 16000 23504 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:36:12,468 autoreload 20160 21572 Watching for file changes with StatReloader
INFO 2024-03-13 15:36:19,907 autoreload 20160 21572 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:36:35,124 autoreload 16028 9980 Watching for file changes with StatReloader
INFO 2024-03-13 15:36:40,166 autoreload 16028 9980 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:36:42,206 autoreload 23420 15872 Watching for file changes with StatReloader
DEBUG 2024-03-13 15:36:44,331 views 23420 13092 <WSGIRequest: GET '/'>
INFO 2024-03-13 15:36:44,410 basehttp 23420 13092 "GET / HTTP/1.1" 200 249
ERROR 2024-03-13 15:36:54,122 log 23420 16164 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 23, in orders_week
    date_diff = new_date2 - new_date1
                ~~~~~~~~~~^~~~~~~~~~~
TypeError: can't subtract offset-naive and offset-aware datetimes
ERROR 2024-03-13 15:36:54,155 basehttp 23420 16164 "GET /orders/2/week/ HTTP/1.1" 500 67701
INFO 2024-03-13 15:37:24,077 autoreload 23420 15872 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:37:25,907 autoreload 16636 17216 Watching for file changes with StatReloader
ERROR 2024-03-13 15:37:29,408 log 16636 6916 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 27, in orders_week
    for product,  in order.products.all():
        ^^^^^^^^
TypeError: cannot unpack non-iterable Product object
ERROR 2024-03-13 15:37:29,422 basehttp 16636 6916 "GET /orders/2/week/ HTTP/1.1" 500 67931
INFO 2024-03-13 15:39:10,762 autoreload 16636 17216 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:39:12,510 autoreload 12956 6820 Watching for file changes with StatReloader
ERROR 2024-03-13 15:39:16,977 log 12956 17704 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 23, in orders_week
    date_diff = (datetime.now().replace(zinfo=timezone('UTC')) - order.date_ordered).days
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'zinfo' is an invalid keyword argument for replace()
ERROR 2024-03-13 15:39:16,992 basehttp 12956 17704 "GET /orders/2/week/ HTTP/1.1" 500 67455
INFO 2024-03-13 15:39:46,250 autoreload 12956 6820 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:39:48,193 autoreload 17428 2560 Watching for file changes with StatReloader
ERROR 2024-03-13 15:39:54,833 log 17428 22352 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 24, in orders_week
    print(date_diff.days)
          ^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'days'
ERROR 2024-03-13 15:39:54,852 basehttp 17428 22352 "GET /orders/2/week/ HTTP/1.1" 500 67513
INFO 2024-03-13 15:40:38,572 autoreload 17428 2560 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:40:40,476 autoreload 16516 17888 Watching for file changes with StatReloader
ERROR 2024-03-13 15:40:44,118 log 16516 14000 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 23, in orders_week
    date_diff = (datetime.now().replace(tzinfo=timezone('UTC')) - order.date_ordered).days
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
ERROR 2024-03-13 15:40:44,128 basehttp 16516 14000 "GET /orders/2/week/ HTTP/1.1" 500 68081
INFO 2024-03-13 15:41:50,086 autoreload 16516 17888 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:41:52,294 autoreload 12448 19776 Watching for file changes with StatReloader
ERROR 2024-03-13 15:41:56,010 log 12448 5176 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 23, in orders_week
    date_diff = (new_date2 - new_date1).days
                 ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
ERROR 2024-03-13 15:41:56,028 basehttp 12448 5176 "GET /orders/2/week/ HTTP/1.1" 500 68248
INFO 2024-03-13 15:42:21,539 autoreload 12448 19776 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:42:23,396 autoreload 15052 20444 Watching for file changes with StatReloader
ERROR 2024-03-13 15:42:27,275 log 15052 11600 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 25, in orders_week
    if date_diff < 31:
       ^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'datetime.timedelta' and 'int'
ERROR 2024-03-13 15:42:27,307 basehttp 15052 11600 "GET /orders/2/week/ HTTP/1.1" 500 68066
INFO 2024-03-13 15:43:15,678 autoreload 15052 20444 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:43:17,458 autoreload 10860 16336 Watching for file changes with StatReloader
ERROR 2024-03-13 15:43:20,780 log 10860 9632 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 23, in orders_week
    date_diff = new_date2 - new_date1
                ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
ERROR 2024-03-13 15:43:20,794 basehttp 10860 9632 "GET /orders/2/week/ HTTP/1.1" 500 68290
INFO 2024-03-13 15:43:57,176 autoreload 10860 16336 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:43:59,019 autoreload 14580 9120 Watching for file changes with StatReloader
ERROR 2024-03-13 15:44:05,468 log 14580 19780 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 24, in orders_week
    date_diff = new_date2 - new_date1
                ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
ERROR 2024-03-13 15:44:05,475 basehttp 14580 19780 "GET /orders/2/week/ HTTP/1.1" 500 68309
INFO 2024-03-13 15:44:42,661 autoreload 14580 9120 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:44:54,035 autoreload 18024 9036 Watching for file changes with StatReloader
ERROR 2024-03-13 15:44:57,914 log 18024 11016 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 20, in orders_week
    new_date1 = datetime(order.date_ordered)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'datetime.datetime' object cannot be interpreted as an integer
ERROR 2024-03-13 15:44:57,981 basehttp 18024 11016 "GET /orders/2/week/ HTTP/1.1" 500 67353
INFO 2024-03-13 15:46:20,105 autoreload 18024 9036 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:46:22,188 autoreload 14120 16116 Watching for file changes with StatReloader
INFO 2024-03-13 15:46:31,583 autoreload 14784 16028 Watching for file changes with StatReloader
ERROR 2024-03-13 15:46:40,018 log 14784 18240 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 24, in orders_week
    date_diff = new_date2 - new_date1
                ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
ERROR 2024-03-13 15:46:40,125 basehttp 14784 18240 "GET /orders/2/week/ HTTP/1.1" 500 68310
INFO 2024-03-13 15:47:35,568 autoreload 14784 16028 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 15:47:37,256 autoreload 7100 3584 Watching for file changes with StatReloader
ERROR 2024-03-13 15:47:41,557 log 7100 18808 Internal Server Error: /orders/2/week/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 24, in orders_week
    date_diff = new_date2 - new_date1
                ~~~~~~~~~~^~~~~~~~~~~
TypeError: unsupported operand type(s) for -: 'datetime.datetime' and 'NoneType'
ERROR 2024-03-13 15:47:41,567 basehttp 7100 18808 "GET /orders/2/week/ HTTP/1.1" 500 68324
INFO 2024-03-13 15:59:03,674 autoreload 17568 6124 Watching for file changes with StatReloader
INFO 2024-03-13 15:59:10,326 basehttp 17568 8508 "GET /orders/2/week/ HTTP/1.1" 200 403
INFO 2024-03-13 16:01:12,844 autoreload 17568 6124 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 16:01:15,281 autoreload 20012 17888 Watching for file changes with StatReloader
DEBUG 2024-03-13 16:01:32,278 views 20012 10036 <WSGIRequest: GET '/'>
INFO 2024-03-13 16:01:32,296 basehttp 20012 10036 "GET / HTTP/1.1" 200 249
DEBUG 2024-03-13 16:01:32,918 views 20012 10036 <WSGIRequest: GET '/'>
INFO 2024-03-13 16:01:32,920 basehttp 20012 10036 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 16:01:33,636 log 20012 10036 Not Found: /favicon.ico
WARNING 2024-03-13 16:01:33,683 basehttp 20012 10036 "GET /favicon.ico HTTP/1.1" 404 4298
INFO 2024-03-13 16:01:36,931 basehttp 20012 10036 "GET /orders/2/week/ HTTP/1.1" 200 403
INFO 2024-03-13 16:03:27,397 autoreload 20012 17888 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 16:03:29,200 autoreload 21360 9092 Watching for file changes with StatReloader
DEBUG 2024-03-13 16:03:31,870 views 21360 7308 <WSGIRequest: GET '/'>
INFO 2024-03-13 16:03:31,893 basehttp 21360 7308 "GET / HTTP/1.1" 200 249
INFO 2024-03-13 16:03:43,156 basehttp 21360 20324 "GET /orders/2/week/ HTTP/1.1" 200 507
INFO 2024-03-13 16:05:09,538 basehttp 21360 4432 "GET /orders/2/week/ HTTP/1.1" 200 1119
INFO 2024-03-13 16:07:01,281 autoreload 21360 9092 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 16:07:03,327 autoreload 8428 10740 Watching for file changes with StatReloader
INFO 2024-03-13 16:08:48,423 autoreload 2264 17264 Watching for file changes with StatReloader
INFO 2024-03-13 16:08:50,082 basehttp 2264 7936 "GET /orders/2/week/ HTTP/1.1" 200 921
INFO 2024-03-13 16:10:38,251 basehttp 2264 1104 "GET /orders/2/week/ HTTP/1.1" 200 921
ERROR 2024-03-13 16:10:45,576 log 2264 1104 Internal Server Error: /orders/2/month/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 43, in orders_month
    return render(request, 'myapp2/orders_week.html', context=context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\defaulttags.py", line 230, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 1. 
ERROR 2024-03-13 16:10:45,592 basehttp 2264 1104 "GET /orders/2/month/ HTTP/1.1" 500 139645
INFO 2024-03-13 16:12:26,272 autoreload 2264 17264 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 16:12:28,569 autoreload 14860 9256 Watching for file changes with StatReloader
INFO 2024-03-13 16:12:47,105 autoreload 14860 9256 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 16:12:48,666 autoreload 16312 16576 Watching for file changes with StatReloader
DEBUG 2024-03-13 16:12:58,207 views 16312 13960 <WSGIRequest: GET '/'>
INFO 2024-03-13 16:12:58,276 basehttp 16312 13960 "GET / HTTP/1.1" 200 249
DEBUG 2024-03-13 16:12:58,724 views 16312 13960 <WSGIRequest: GET '/'>
INFO 2024-03-13 16:12:58,726 basehttp 16312 13960 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 16:12:59,379 log 16312 13960 Not Found: /favicon.ico
WARNING 2024-03-13 16:12:59,798 basehttp 16312 13960 "GET /favicon.ico HTTP/1.1" 404 4298
WARNING 2024-03-13 16:13:00,321 log 16312 440 Not Found: /favicon.ico
WARNING 2024-03-13 16:13:00,526 basehttp 16312 440 "GET /favicon.ico HTTP/1.1" 404 4298
INFO 2024-03-13 16:13:04,258 basehttp 16312 13444 "GET /orders/2/week/ HTTP/1.1" 200 921
INFO 2024-03-13 16:13:12,976 basehttp 16312 564 "GET /orders/2/month/ HTTP/1.1" 200 1792
INFO 2024-03-13 16:13:24,365 basehttp 16312 18636 "GET /orders/2/year/ HTTP/1.1" 200 3312
INFO 2024-03-13 16:17:05,364 autoreload 20880 15472 Watching for file changes with StatReloader
DEBUG 2024-03-13 16:17:11,259 views 20880 15120 <WSGIRequest: GET '/'>
INFO 2024-03-13 16:17:11,378 basehttp 20880 15120 "GET / HTTP/1.1" 200 249
WARNING 2024-03-13 16:17:12,063 log 20880 15120 Not Found: /favicon.ico
WARNING 2024-03-13 16:17:12,100 basehttp 20880 15120 "GET /favicon.ico HTTP/1.1" 404 4298
INFO 2024-03-13 16:17:18,483 basehttp 20880 21024 "GET /orders/2/week/ HTTP/1.1" 200 946
INFO 2024-03-13 16:17:26,194 basehttp 20880 21024 "GET /orders/2/month/ HTTP/1.1" 200 1817
INFO 2024-03-13 16:17:37,349 basehttp 20880 18360 "GET /orders/2/year/ HTTP/1.1" 200 3337
INFO 2024-03-13 16:18:40,352 autoreload 20880 15472 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-13 16:18:42,066 autoreload 13836 11520 Watching for file changes with StatReloader
INFO 2024-03-13 16:18:45,582 basehttp 13836 1884 "GET /orders/2/year/ HTTP/1.1" 200 3306
INFO 2024-03-13 16:18:54,524 basehttp 13836 21512 "GET /orders/2/month/ HTTP/1.1" 200 1790
INFO 2024-03-13 16:19:08,013 basehttp 13836 18780 "GET /orders/2/week/ HTTP/1.1" 200 921
INFO 2024-03-15 16:28:23,587 autoreload 10084 12348 Watching for file changes with StatReloader
INFO 2024-03-15 16:29:21,363 autoreload 10084 12348 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\forms.py changed, reloading.
INFO 2024-03-15 16:29:23,137 autoreload 3016 11312 Watching for file changes with StatReloader
INFO 2024-03-15 16:30:34,351 autoreload 6128 2248 Watching for file changes with StatReloader
INFO 2024-03-15 16:32:00,620 autoreload 3568 9616 Watching for file changes with StatReloader
INFO 2024-03-15 16:32:45,858 autoreload 9096 8548 Watching for file changes with StatReloader
INFO 2024-03-15 16:33:31,452 autoreload 9096 8548 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-15 16:33:33,205 autoreload 14196 496 Watching for file changes with StatReloader
INFO 2024-03-15 16:35:55,041 autoreload 14196 496 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp5\forms.py changed, reloading.
INFO 2024-03-15 16:35:56,888 autoreload 13564 8088 Watching for file changes with StatReloader
INFO 2024-03-15 16:36:07,727 autoreload 13564 8088 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp5\forms.py changed, reloading.
INFO 2024-03-15 16:36:09,526 autoreload 7888 11128 Watching for file changes with StatReloader
DEBUG 2024-03-15 16:36:12,582 views 7888 7512 <WSGIRequest: GET '/'>
INFO 2024-03-15 16:36:12,673 basehttp 7888 7512 "GET / HTTP/1.1" 200 249
WARNING 2024-03-15 16:36:13,824 log 7888 5720 Not Found: /favicon.ico
WARNING 2024-03-15 16:36:13,838 basehttp 7888 5720 "GET /favicon.ico HTTP/1.1" 404 4999
INFO 2024-03-15 16:36:28,150 basehttp 7888 8056 "GET /product/add HTTP/1.1" 200 1119
INFO 2024-03-15 16:39:06,958 basehttp 7888 11292 "POST /product/add HTTP/1.1" 200 1277
INFO 2024-03-15 16:39:19,043 basehttp 7888 8740 "POST /product/add HTTP/1.1" 200 1277
INFO 2024-03-15 16:40:01,641 autoreload 7888 11128 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-15 16:40:05,106 autoreload 11096 13380 Watching for file changes with StatReloader
INFO 2024-03-15 16:40:11,923 basehttp 11096 6208 "GET /product/add HTTP/1.1" 200 1119
INFO 2024-03-15 16:40:37,633 basehttp 11096 13532 "POST /product/add HTTP/1.1" 200 1257
INFO 2024-03-15 16:41:27,734 autoreload 11096 13380 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-15 16:41:29,405 autoreload 11848 12380 Watching for file changes with StatReloader
INFO 2024-03-15 16:41:34,425 basehttp 11848 14124 "GET /product/add HTTP/1.1" 200 1119
INFO 2024-03-15 16:41:46,587 basehttp 11848 12020 "POST /product/add HTTP/1.1" 200 1236
INFO 2024-03-15 16:42:18,128 autoreload 11848 12380 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py changed, reloading.
INFO 2024-03-15 16:42:21,790 autoreload 12812 6056 Watching for file changes with StatReloader
DEBUG 2024-03-15 16:44:01,873 views 12812 10944 <WSGIRequest: GET '/'>
INFO 2024-03-15 16:44:02,026 basehttp 12812 10944 "GET / HTTP/1.1" 200 249
INFO 2024-03-15 16:44:11,390 basehttp 12812 8036 "GET /product/add HTTP/1.1" 200 1149
ERROR 2024-03-15 16:44:44,910 log 12812 11624 Internal Server Error: /product/add
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: table myapp2_product has no column named image

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\views.py", line 79, in add_product
    Product(**form.cleaned_data).save()
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\base.py", line 822, in save
    self.save_base(
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\base.py", line 1067, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\base.py", line 1108, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: table myapp2_product has no column named image
ERROR 2024-03-15 16:44:44,979 basehttp 12812 11624 "POST /product/add HTTP/1.1" 500 151462
INFO 2024-03-15 16:48:30,076 autoreload 7824 10852 Watching for file changes with StatReloader
DEBUG 2024-03-15 16:48:33,300 views 7824 7176 <WSGIRequest: GET '/'>
INFO 2024-03-15 16:48:33,336 basehttp 7824 7176 "GET / HTTP/1.1" 200 249
INFO 2024-03-15 16:48:42,128 basehttp 7824 5760 "GET /product/add HTTP/1.1" 200 1149
INFO 2024-03-15 16:49:06,448 basehttp 7824 10720 "POST /product/add HTTP/1.1" 200 1194
INFO 2024-03-15 16:49:38,384 basehttp 7824 11100 "POST /product/add HTTP/1.1" 200 1194
INFO 2024-03-15 16:49:53,269 basehttp 7824 7604 "POST /product/add HTTP/1.1" 200 1194
INFO 2024-03-15 16:50:56,841 basehttp 7824 10104 "POST /product/add HTTP/1.1" 200 1194
INFO 2024-03-16 10:53:36,789 autoreload 14712 14308 Watching for file changes with StatReloader
DEBUG 2024-03-16 10:53:40,076 views 14712 4860 <WSGIRequest: GET '/'>
INFO 2024-03-16 10:53:40,566 basehttp 14712 4860 "GET / HTTP/1.1" 200 249
WARNING 2024-03-16 10:53:42,488 log 14712 4860 Not Found: /favicon.ico
WARNING 2024-03-16 10:53:42,599 basehttp 14712 4860 "GET /favicon.ico HTTP/1.1" 404 5176
INFO 2024-03-16 10:53:51,412 basehttp 14712 13060 "GET /products/ HTTP/1.1" 200 2601
INFO 2024-03-18 12:07:37,483 autoreload 11144 16444 Watching for file changes with StatReloader
DEBUG 2024-03-18 12:07:42,637 views 11144 4636 <WSGIRequest: GET '/'>
INFO 2024-03-18 12:07:42,768 basehttp 11144 4636 "GET / HTTP/1.1" 200 249
WARNING 2024-03-18 12:07:49,894 log 11144 528 Not Found: /favicon.ico
WARNING 2024-03-18 12:07:50,038 basehttp 11144 528 "GET /favicon.ico HTTP/1.1" 404 5176
DEBUG 2024-03-18 12:08:12,065 views 11144 9388 <WSGIRequest: GET '/'>
INFO 2024-03-18 12:08:12,069 basehttp 11144 9388 "GET / HTTP/1.1" 200 249
WARNING 2024-03-18 12:08:26,276 log 11144 15812 Not Found: /favicon.ico
WARNING 2024-03-18 12:08:26,770 basehttp 11144 15812 "GET /favicon.ico HTTP/1.1" 404 5176
INFO 2024-03-18 12:10:15,897 autoreload 11144 16444 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-18 12:10:20,974 autoreload 12268 17200 Watching for file changes with StatReloader
INFO 2024-03-18 12:50:26,107 autoreload 17168 8660 Watching for file changes with StatReloader
DEBUG 2024-03-18 12:50:28,796 views 17168 9692 <WSGIRequest: GET '/'>
INFO 2024-03-18 12:50:28,834 basehttp 17168 9692 "GET / HTTP/1.1" 200 249
INFO 2024-03-18 12:50:36,174 basehttp 17168 9692 "GET /admin HTTP/1.1" 301 0
INFO 2024-03-18 12:50:36,207 basehttp 17168 11056 "GET /admin/ HTTP/1.1" 302 0
INFO 2024-03-18 12:50:36,337 basehttp 17168 11056 "GET /admin/login/?next=/admin/ HTTP/1.1" 200 4359
INFO 2024-03-18 12:50:36,757 basehttp 17168 11056 "GET /static/admin/css/base.css HTTP/1.1" 200 21544
INFO 2024-03-18 12:50:36,913 basehttp 17168 5960 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
INFO 2024-03-18 12:50:37,010 basehttp 17168 9248 "GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
INFO 2024-03-18 12:50:37,043 basehttp 17168 4144 "GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
INFO 2024-03-18 12:50:37,112 basehttp 17168 6348 "GET /static/admin/js/theme.js HTTP/1.1" 200 1943
INFO 2024-03-18 12:50:37,114 basehttp 17168 14532 "GET /static/admin/css/login.css HTTP/1.1" 200 958
INFO 2024-03-18 12:50:37,151 basehttp 17168 5960 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
INFO 2024-03-18 12:50:45,517 basehttp 17168 5960 "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
INFO 2024-03-18 12:50:45,583 basehttp 17168 5960 "GET /admin/ HTTP/1.1" 200 7084
INFO 2024-03-18 12:50:45,692 basehttp 17168 5960 "GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
INFO 2024-03-18 12:50:45,734 basehttp 17168 5960 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
INFO 2024-03-18 12:50:45,743 basehttp 17168 14532 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
INFO 2024-03-18 12:50:53,802 basehttp 17168 14532 "GET /admin/myapp6/category/add/ HTTP/1.1" 200 9112
INFO 2024-03-18 12:50:53,943 basehttp 17168 4144 "GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
INFO 2024-03-18 12:50:53,962 basehttp 17168 6348 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
INFO 2024-03-18 12:50:53,964 basehttp 17168 11056 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
INFO 2024-03-18 12:50:53,978 basehttp 17168 9248 "GET /static/admin/js/core.js HTTP/1.1" 200 6208
INFO 2024-03-18 12:50:53,984 basehttp 17168 5960 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-18 12:50:53,992 basehttp 17168 14532 "GET /static/admin/css/forms.css HTTP/1.1" 200 9090
INFO 2024-03-18 12:50:54,027 basehttp 17168 4144 "GET /static/admin/js/actions.js HTTP/1.1" 200 8067
INFO 2024-03-18 12:50:54,057 basehttp 17168 11056 "GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
INFO 2024-03-18 12:50:54,129 basehttp 17168 6348 "GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
INFO 2024-03-18 12:50:54,185 basehttp 17168 9248 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
INFO 2024-03-18 12:50:54,235 basehttp 17168 5960 "GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
INFO 2024-03-18 12:50:54,684 basehttp 17168 14532 "GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
INFO 2024-03-18 12:50:54,807 basehttp 17168 9248 "GET /static/admin/js/change_form.js HTTP/1.1" 200 606
ERROR 2024-03-18 12:51:09,580 log 17168 7464 Internal Server Error: /admin/myapp6/category/add/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: myapp6_category

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1945, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1804, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1849, in _changeform_view
    form_validated = form.is_valid()
                     ^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\forms\forms.py", line 197, in is_valid
    return self.is_bound and not self.errors
                                 ^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\forms\forms.py", line 192, in errors
    self.full_clean()
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\forms\forms.py", line 329, in full_clean
    self._post_clean()
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\forms\models.py", line 502, in _post_clean
    self.validate_unique()
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\forms\models.py", line 511, in validate_unique
    self.instance.validate_unique(exclude=exclude)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\base.py", line 1279, in validate_unique
    errors = self._perform_unique_checks(unique_checks)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\base.py", line 1389, in _perform_unique_checks
    if qs.exists():
       ^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 1288, in exists
    return self.query.has_results(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\query.py", line 659, in has_results
    return compiler.has_results()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1530, in has_results
    return bool(self.execute_sql(SINGLE))
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: myapp6_category
ERROR 2024-03-18 12:51:09,997 basehttp 17168 7464 "POST /admin/myapp6/category/add/ HTTP/1.1" 500 210339
INFO 2024-03-19 11:48:57,585 autoreload 512 15588 Watching for file changes with StatReloader
DEBUG 2024-03-19 11:49:03,818 views 512 8932 <WSGIRequest: GET '/'>
INFO 2024-03-19 11:49:03,856 basehttp 512 8932 "GET / HTTP/1.1" 200 249
INFO 2024-03-19 11:49:18,450 basehttp 512 12836 "GET /admin/ HTTP/1.1" 200 7084
INFO 2024-03-19 11:53:33,861 autoreload 512 15588 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\admin.py changed, reloading.
INFO 2024-03-19 11:53:39,912 autoreload 7112 8388 Watching for file changes with StatReloader
INFO 2024-03-19 11:55:15,004 autoreload 7112 8388 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-19 11:55:22,530 autoreload 9572 13336 Watching for file changes with StatReloader
INFO 2024-03-19 12:22:23,841 autoreload 13112 2760 Watching for file changes with StatReloader
INFO 2024-03-19 12:23:08,636 autoreload 13112 2760 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-19 12:23:10,570 autoreload 2324 3632 Watching for file changes with StatReloader
INFO 2024-03-19 12:24:04,364 autoreload 2324 3632 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-19 12:24:06,042 autoreload 8876 8936 Watching for file changes with StatReloader
DEBUG 2024-03-19 12:24:08,856 views 8876 15680 <WSGIRequest: GET '/'>
INFO 2024-03-19 12:24:09,023 basehttp 8876 15680 "GET / HTTP/1.1" 200 249
INFO 2024-03-19 12:24:25,694 basehttp 8876 14568 "GET /admin/ HTTP/1.1" 200 7527
ERROR 2024-03-19 12:24:36,476 log 8876 15524 Internal Server Error: /admin/myapp6/author/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: myapp6_author

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 716, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\views\decorators\cache.py", line 80, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\sites.py", line 240, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 188, in _view_wrapper
    result = _process_exception(request, e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\decorators.py", line 186, in _view_wrapper
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 1985, in changelist_view
    cl = self.get_changelist_instance(request)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 864, in get_changelist_instance
    return ChangeList(
           ^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 145, in __init__
    self.get_results(request)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\views\main.py", line 312, in get_results
    result_count = paginator.count
                   ^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\functional.py", line 47, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\paginator.py", line 110, in count
    return c()
           ^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\query.py", line 620, in count
    return self.query.get_count(using=self.db)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\query.py", line 629, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\query.py", line 615, in get_aggregation
    result = compiler.execute_sql(SINGLE)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\backends\sqlite3\base.py", line 329, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: myapp6_author
ERROR 2024-03-19 12:24:36,634 basehttp 8876 15524 "GET /admin/myapp6/author/ HTTP/1.1" 500 195363
INFO 2024-03-19 12:25:41,169 autoreload 9832 9696 Watching for file changes with StatReloader
INFO 2024-03-19 12:25:49,506 basehttp 9832 6520 "GET /admin/ HTTP/1.1" 200 7527
INFO 2024-03-19 12:25:51,418 basehttp 9832 6520 "GET /admin/myapp6/author/ HTTP/1.1" 200 10584
INFO 2024-03-19 12:25:51,811 basehttp 9832 1420 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-19 12:25:51,865 basehttp 9832 1204 "GET /static/admin/js/calendar.js HTTP/1.1" 200 9141
INFO 2024-03-19 12:25:51,903 basehttp 9832 6520 "GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
INFO 2024-03-19 12:25:51,938 basehttp 9832 11940 "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19319
INFO 2024-03-19 12:25:52,061 basehttp 9832 11940 "GET /static/admin/js/filters.js HTTP/1.1" 200 978
INFO 2024-03-19 12:25:52,065 basehttp 9832 8576 "GET /static/admin/img/search.svg HTTP/1.1" 200 458
INFO 2024-03-19 12:25:52,134 basehttp 9832 8576 "GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
INFO 2024-03-19 12:25:52,136 basehttp 9832 11940 "GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
INFO 2024-03-19 12:26:21,891 basehttp 9832 6692 "GET /admin/myapp6/author/? HTTP/1.1" 200 10584
INFO 2024-03-19 12:26:22,325 basehttp 9832 6692 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-19 12:26:36,751 basehttp 9832 14944 "GET /admin/myapp6/author/?q=Name HTTP/1.1" 200 10690
INFO 2024-03-19 12:26:36,845 basehttp 9832 14944 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-19 12:26:43,542 basehttp 9832 14944 "GET /admin/myapp6/author/? HTTP/1.1" 200 10584
INFO 2024-03-19 12:38:30,091 autoreload 9832 9696 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-19 12:38:33,058 autoreload 16792 13916 Watching for file changes with StatReloader
INFO 2024-03-19 14:33:56,886 autoreload 16792 13916 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-19 14:34:01,927 autoreload 8840 8760 Watching for file changes with StatReloader
INFO 2024-03-19 14:39:36,236 autoreload 8840 8760 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-19 14:39:41,245 autoreload 16604 5488 Watching for file changes with StatReloader
INFO 2024-03-20 10:55:14,863 autoreload 17180 9260 Watching for file changes with StatReloader
INFO 2024-03-20 10:56:37,492 autoreload 3260 11140 Watching for file changes with StatReloader
INFO 2024-03-20 10:57:24,688 autoreload 3260 11140 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-20 10:57:27,980 autoreload 16612 12936 Watching for file changes with StatReloader
INFO 2024-03-20 10:58:53,382 autoreload 16612 12936 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\admin.py changed, reloading.
INFO 2024-03-20 10:58:56,016 autoreload 16260 8188 Watching for file changes with StatReloader
INFO 2024-03-20 10:59:30,989 autoreload 16260 8188 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-20 10:59:34,335 autoreload 3752 16832 Watching for file changes with StatReloader
INFO 2024-03-20 10:59:51,498 autoreload 3752 16832 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\admin.py changed, reloading.
INFO 2024-03-20 10:59:53,641 autoreload 3988 15408 Watching for file changes with StatReloader
INFO 2024-03-20 11:00:15,020 autoreload 3988 15408 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\admin.py changed, reloading.
INFO 2024-03-20 11:00:17,327 autoreload 12996 15860 Watching for file changes with StatReloader
INFO 2024-03-20 11:02:22,846 autoreload 12996 15860 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-20 11:02:26,205 autoreload 6776 13984 Watching for file changes with StatReloader
DEBUG 2024-03-20 11:02:38,682 views 6776 15716 <WSGIRequest: GET '/'>
INFO 2024-03-20 11:02:38,730 basehttp 6776 15716 "GET / HTTP/1.1" 200 249
WARNING 2024-03-20 11:02:40,356 log 6776 15716 Not Found: /favicon.ico
WARNING 2024-03-20 11:02:40,732 basehttp 6776 15716 "GET /favicon.ico HTTP/1.1" 404 5176
INFO 2024-03-20 11:02:47,527 basehttp 6776 11308 "GET /admin/ HTTP/1.1" 200 7512
INFO 2024-03-20 11:02:47,662 basehttp 6776 8564 "GET /static/admin/css/dark_mode.css HTTP/1.1" 304 0
INFO 2024-03-20 11:02:47,757 basehttp 6776 11308 "GET /static/admin/css/base.css HTTP/1.1" 304 0
INFO 2024-03-20 11:02:47,900 basehttp 6776 16028 "GET /static/admin/css/nav_sidebar.css HTTP/1.1" 304 0
INFO 2024-03-20 11:02:48,033 basehttp 6776 18104 "GET /static/admin/css/dashboard.css HTTP/1.1" 304 0
INFO 2024-03-20 11:02:48,045 basehttp 6776 16028 "GET /static/admin/js/nav_sidebar.js HTTP/1.1" 304 0
INFO 2024-03-20 11:02:48,093 basehttp 6776 12376 "GET /static/admin/css/responsive.css HTTP/1.1" 304 0
INFO 2024-03-20 11:02:48,227 basehttp 6776 8588 "GET /static/admin/js/theme.js HTTP/1.1" 304 0
INFO 2024-03-20 11:02:48,797 basehttp 6776 8588 "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 304 0
INFO 2024-03-20 11:02:48,798 basehttp 6776 12376 "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 304 0
ERROR 2024-03-20 11:02:56,719 log 6776 12376 Internal Server Error: /admin/myapp2/client/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 289, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 322, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Client has no field named 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 345, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in __init__
    super().__init__(*items)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 298, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 999, in action_checkbox
    "aria-label": format_html(_("Select this object for an action - {}"), obj),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\html.py", line 135, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\html.py", line 117, in conditional_escape
    return escape(text)
           ^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\functional.py", line 231, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\html.py", line 50, in escape
    return SafeString(html.escape(str(text)))
                                  ^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 18, in __str__
    f'registration_date: {self}')
                         ^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 18, in __str__
    f'registration_date: {self}')
                         ^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 18, in __str__
    f'registration_date: {self}')
                         ^^^^^^
  [Previous line repeated 361 more times]
RecursionError: maximum recursion depth exceeded while getting the str of an object
ERROR 2024-03-20 11:02:57,065 basehttp 6776 12376 "GET /admin/myapp2/client/ HTTP/1.1" 500 1700410
INFO 2024-03-20 11:03:30,415 basehttp 6776 10508 "GET /admin/ HTTP/1.1" 200 7512
INFO 2024-03-20 11:03:31,511 basehttp 6776 10508 "GET /admin/ HTTP/1.1" 200 7512
INFO 2024-03-20 11:03:32,933 basehttp 6776 10508 "GET /admin/myapp2/order/ HTTP/1.1" 200 15436
INFO 2024-03-20 11:03:33,078 basehttp 6776 15228 "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,112 basehttp 6776 10508 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:03:33,131 basehttp 6776 15228 "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,136 basehttp 6776 10508 "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,155 basehttp 6776 16468 "GET /static/admin/js/actions.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,170 basehttp 6776 15228 "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,344 basehttp 6776 7896 "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,414 basehttp 6776 8928 "GET /static/admin/js/core.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:33,483 basehttp 6776 18024 "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
INFO 2024-03-20 11:03:38,856 basehttp 6776 15156 "GET /admin/ HTTP/1.1" 200 7512
INFO 2024-03-20 11:03:40,180 basehttp 6776 15156 "GET /admin/myapp2/product/ HTTP/1.1" 200 14721
INFO 2024-03-20 11:03:40,274 basehttp 6776 15156 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-03-20 11:03:46,914 log 6776 3300 Internal Server Error: /admin/myapp2/client/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 289, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 322, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Client has no field named 'action_checkbox'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 345, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in __init__
    super().__init__(*items)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 298, in lookup_field
    value = attr(obj)
            ^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\options.py", line 999, in action_checkbox
    "aria-label": format_html(_("Select this object for an action - {}"), obj),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\html.py", line 135, in format_html
    return mark_safe(format_string.format(*args_safe, **kwargs_safe))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\html.py", line 117, in conditional_escape
    return escape(text)
           ^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\functional.py", line 231, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\html.py", line 50, in escape
    return SafeString(html.escape(str(text)))
                                  ^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 18, in __str__
    f'registration_date: {self}')
                         ^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 18, in __str__
    f'registration_date: {self}')
                         ^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 18, in __str__
    f'registration_date: {self}')
                         ^^^^^^
  [Previous line repeated 361 more times]
RecursionError: maximum recursion depth exceeded while getting the str of an object
ERROR 2024-03-20 11:03:47,001 basehttp 6776 3300 "GET /admin/myapp2/client/ HTTP/1.1" 500 1700425
INFO 2024-03-20 11:04:53,703 autoreload 6776 13984 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py changed, reloading.
INFO 2024-03-20 11:04:56,590 autoreload 15456 12628 Watching for file changes with StatReloader
INFO 2024-03-20 11:05:08,664 autoreload 15456 12628 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py changed, reloading.
INFO 2024-03-20 11:05:11,146 autoreload 10448 13756 Watching for file changes with StatReloader
INFO 2024-03-20 11:05:20,477 basehttp 10448 17620 "GET /admin/myapp2/product/ HTTP/1.1" 200 14721
INFO 2024-03-20 11:05:22,278 basehttp 10448 17620 "GET /admin/myapp2/client/ HTTP/1.1" 200 14312
INFO 2024-03-20 11:05:22,621 basehttp 10448 17620 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:10:30,662 autoreload 10448 13756 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:10:34,822 autoreload 15820 15308 Watching for file changes with StatReloader
INFO 2024-03-20 11:10:40,289 basehttp 15820 17472 "GET /admin/myapp2/product/ HTTP/1.1" 200 18422
INFO 2024-03-20 11:10:43,227 basehttp 15820 17472 "GET /admin/myapp2/product/ HTTP/1.1" 200 18422
INFO 2024-03-20 11:10:43,879 basehttp 15820 17472 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:11:48,131 autoreload 15820 15308 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:11:50,640 autoreload 9840 7512 Watching for file changes with StatReloader
INFO 2024-03-20 11:11:56,011 basehttp 9840 16968 "GET /admin/myapp2/product/ HTTP/1.1" 200 19220
INFO 2024-03-20 11:11:56,141 basehttp 9840 16968 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:11:56,578 basehttp 9840 16968 "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
INFO 2024-03-20 11:12:51,008 autoreload 9840 7512 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:12:54,441 autoreload 15668 6192 Watching for file changes with StatReloader
INFO 2024-03-20 11:13:00,802 basehttp 15668 13604 "GET /admin/myapp2/product/ HTTP/1.1" 200 20869
INFO 2024-03-20 11:13:00,859 basehttp 15668 13604 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:13:55,017 autoreload 15668 6192 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:14:00,645 autoreload 16656 17636 Watching for file changes with StatReloader
INFO 2024-03-20 11:14:01,843 basehttp 16656 16704 "GET /admin/myapp2/product/ HTTP/1.1" 200 21512
INFO 2024-03-20 11:14:02,330 basehttp 16656 16704 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:14:29,206 autoreload 16656 17636 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:14:36,685 autoreload 5112 10804 Watching for file changes with StatReloader
INFO 2024-03-20 11:14:59,476 autoreload 5112 10804 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:15:02,179 autoreload 9116 6424 Watching for file changes with StatReloader
INFO 2024-03-20 11:15:31,453 autoreload 9116 6424 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:15:34,291 autoreload 15144 3896 Watching for file changes with StatReloader
INFO 2024-03-20 11:15:38,462 basehttp 15144 17376 "GET /admin/myapp2/product/ HTTP/1.1" 200 22020
INFO 2024-03-20 11:15:38,937 basehttp 15144 17376 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:22:36,338 autoreload 15144 3896 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:22:38,989 autoreload 10684 10216 Watching for file changes with StatReloader
INFO 2024-03-20 11:23:00,805 autoreload 10684 10216 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:23:03,715 autoreload 4976 1432 Watching for file changes with StatReloader
INFO 2024-03-20 11:23:10,134 basehttp 4976 11856 "GET /admin/myapp2/order/ HTTP/1.1" 200 20875
INFO 2024-03-20 11:23:10,536 basehttp 4976 11856 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:23:19,914 basehttp 4976 7056 "GET /admin/myapp2/client/ HTTP/1.1" 200 17929
INFO 2024-03-20 11:23:20,073 basehttp 4976 7056 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:23:24,837 basehttp 4976 7056 "GET /admin/myapp2/order/ HTTP/1.1" 200 20875
INFO 2024-03-20 11:23:24,992 basehttp 4976 7056 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:23:39,844 basehttp 4976 12536 "GET /admin/myapp2/order/?products__id__exact=11 HTTP/1.1" 200 14511
INFO 2024-03-20 11:23:39,961 basehttp 4976 12536 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:23:45,349 basehttp 4976 12536 "GET /admin/myapp2/order/?products__id__exact=6 HTTP/1.1" 200 17287
INFO 2024-03-20 11:23:45,534 basehttp 4976 12536 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:23:57,673 basehttp 4976 15156 "GET /admin/myapp2/order/? HTTP/1.1" 200 20875
INFO 2024-03-20 11:23:57,824 basehttp 4976 15156 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:24:30,744 autoreload 4976 1432 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:24:33,659 autoreload 5896 14232 Watching for file changes with StatReloader
INFO 2024-03-20 11:32:31,219 autoreload 5896 14232 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:32:39,541 autoreload 14896 6172 Watching for file changes with StatReloader
INFO 2024-03-20 11:32:45,738 autoreload 14896 6172 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\admin.py changed, reloading.
INFO 2024-03-20 11:32:48,327 autoreload 14320 18372 Watching for file changes with StatReloader
INFO 2024-03-20 11:32:54,240 basehttp 14320 3372 "GET /admin/myapp2/product/ HTTP/1.1" 200 22020
INFO 2024-03-20 11:32:54,359 basehttp 14320 3372 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
ERROR 2024-03-20 11:33:00,148 log 14320 7764 Internal Server Error: /admin/myapp2/order/
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\options.py", line 681, in get_field
    return self.fields_map[field_name]
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'get_products'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 289, in lookup_field
    f = _get_non_gfk_field(opts, name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 322, in _get_non_gfk_field
    field = opts.get_field(name)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\db\models\options.py", line 683, in get_field
    raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Order has no field named 'get_products'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\base.py", line 45, in render
    return super().render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\template\library.py", line 258, in render
    _dict = self.func(*resolved_args, **resolved_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 345, in result_list
    "results": list(results(cl)),
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 321, in results
    yield ResultList(None, items_for_result(cl, res, None))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 312, in __init__
    super().__init__(*items)
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\templatetags\admin_list.py", line 217, in items_for_result
    f, attr, value = lookup_field(field_name, result, cl.model_admin)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\admin\utils.py", line 302, in lookup_field
    value = attr()
            ^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py", line 43, in get_products
    return "\n".join([p.products for p in self.products.all()])
                      ^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'products'
ERROR 2024-03-20 11:33:00,556 basehttp 14320 7764 "GET /admin/myapp2/order/ HTTP/1.1" 500 344197
INFO 2024-03-20 11:33:53,814 autoreload 14320 18372 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py changed, reloading.
INFO 2024-03-20 11:33:55,925 autoreload 12936 12864 Watching for file changes with StatReloader
INFO 2024-03-20 11:34:03,970 basehttp 12936 11444 "GET /admin/myapp2/order/ HTTP/1.1" 200 21480
INFO 2024-03-20 11:34:04,145 basehttp 12936 11444 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:34:08,870 basehttp 12936 12608 "GET /admin/myapp2/order/ HTTP/1.1" 200 21480
INFO 2024-03-20 11:34:08,956 basehttp 12936 12608 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:34:53,376 autoreload 12936 12864 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp2\models.py changed, reloading.
INFO 2024-03-20 11:34:56,419 autoreload 13468 2484 Watching for file changes with StatReloader
INFO 2024-03-20 11:35:01,135 basehttp 13468 14020 "GET /admin/myapp2/client/ HTTP/1.1" 200 17256
INFO 2024-03-20 11:35:01,337 basehttp 13468 14020 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 11:35:07,572 basehttp 13468 12400 "GET /admin/myapp2/order/ HTTP/1.1" 200 20204
INFO 2024-03-20 11:35:07,626 basehttp 13468 12400 "GET /admin/jsi18n/ HTTP/1.1" 200 17546
INFO 2024-03-20 12:03:18,792 autoreload 17100 5000 Watching for file changes with StatReloader
INFO 2024-03-20 12:06:04,948 autoreload 17100 5000 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-20 12:06:07,783 autoreload 18060 16856 Watching for file changes with StatReloader
DEBUG 2024-03-20 12:07:05,562 views 18060 13712 <WSGIRequest: GET '/'>
INFO 2024-03-20 12:07:07,516 basehttp 18060 13712 "GET / HTTP/1.1" 200 10065
INFO 2024-03-20 12:07:14,225 basehttp 18060 13712 "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 200 12621
INFO 2024-03-20 12:07:15,012 basehttp 18060 5548 "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 200 13578
INFO 2024-03-20 12:07:15,499 basehttp 18060 5888 "GET /static/debug_toolbar/css/print.css HTTP/1.1" 200 43
INFO 2024-03-20 12:07:16,666 basehttp 18060 5888 "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 200 4527
WARNING 2024-03-20 12:07:25,409 log 18060 5888 Not Found: /favicon.ico
WARNING 2024-03-20 12:07:26,325 basehttp 18060 5888 "GET /favicon.ico HTTP/1.1" 404 15091
DEBUG 2024-03-20 12:07:33,747 views 18060 5888 <WSGIRequest: GET '/'>
INFO 2024-03-20 12:07:33,798 basehttp 18060 5888 "GET / HTTP/1.1" 200 10063
INFO 2024-03-20 12:07:45,999 basehttp 18060 3368 "GET /__debug__/render_panel/?store_id=2b9ca4ba6912432da1185e749febd965&panel_id=HistoryPanel HTTP/1.1" 200 5784
INFO 2024-03-20 12:07:46,187 basehttp 18060 3368 "GET /static/debug_toolbar/js/history.js HTTP/1.1" 200 3515
INFO 2024-03-20 12:29:56,384 autoreload 18060 16856 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\myapp6\models.py changed, reloading.
INFO 2024-03-20 12:29:59,969 autoreload 15540 14324 Watching for file changes with StatReloader
INFO 2024-03-20 13:21:40,210 autoreload 10168 9760 Watching for file changes with StatReloader
DEBUG 2024-03-20 13:21:48,102 views 10168 8856 <WSGIRequest: GET '/'>
INFO 2024-03-20 13:21:48,433 basehttp 10168 8856 "GET / HTTP/1.1" 200 10064
INFO 2024-03-20 13:21:49,375 basehttp 10168 6624 "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
INFO 2024-03-20 13:21:49,375 basehttp 10168 8856 "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
INFO 2024-03-20 13:21:49,726 basehttp 10168 4572 "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
INFO 2024-03-20 13:21:50,045 basehttp 10168 8856 "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
INFO 2024-03-20 13:22:30,194 basehttp 10168 8928 "GET /db/ HTTP/1.1" 200 10181
INFO 2024-03-20 13:24:10,042 basehttp 10168 16640 "GET /view/ HTTP/1.1" 200 10165
INFO 2024-03-20 13:25:16,064 basehttp 10168 13836 "GET /template/ HTTP/1.1" 200 10149
INFO 2024-03-20 13:42:03,281 autoreload 10168 9760 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-20 13:42:11,008 autoreload 10584 16096 Watching for file changes with StatReloader
INFO 2024-03-20 13:50:46,732 autoreload 10584 16096 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-20 13:50:53,111 autoreload 3508 1268 Watching for file changes with StatReloader
INFO 2024-03-20 13:59:50,604 autoreload 3508 1268 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-22 15:15:14,231 autoreload 8332 11664 Watching for file changes with StatReloader
ERROR 2024-03-22 15:15:19,110 log 8332 10468 Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in __init__
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\conf\__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-03-22 15:15:19,325 basehttp 8332 10468 "GET / HTTP/1.1" 500 145
ERROR 2024-03-22 15:15:20,325 log 8332 10468 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\middleware.py", line 12, in process_request
    request._messages = default_storage(request)
                        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\storage\__init__.py", line 12, in default_storage
    return import_string(settings.MESSAGE_STORAGE)(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\storage\fallback.py", line 17, in __init__
    storage_class(*args, **kwargs) for storage_class in self.storage_classes
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\contrib\messages\storage\cookie.py", line 92, in __init__
    self.signer = signing.get_cookie_signer(salt=self.key_salt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\core\signing.py", line 114, in get_cookie_signer
    key=_cookie_signer_key(settings.SECRET_KEY),
                           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\.venv\Lib\site-packages\django\conf\__init__.py", line 98, in __getattr__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
ERROR 2024-03-22 15:15:20,402 basehttp 8332 10468 "GET /favicon.ico HTTP/1.1" 500 145
INFO 2024-03-22 15:15:51,709 autoreload 8332 11664 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-22 15:15:55,173 autoreload 15696 10516 Watching for file changes with StatReloader
ERROR 2024-03-22 15:16:22,672 basehttp 15696 10200 "GET / HTTP/1.1" 500 59
INFO 2024-03-22 15:16:22,822 basehttp 15696 10200 - Broken pipe from ('127.0.0.1', 47876)
ERROR 2024-03-22 15:16:23,878 basehttp 15696 4660 "GET / HTTP/1.1" 500 59
INFO 2024-03-22 15:16:49,103 autoreload 15696 10516 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-22 15:16:53,344 autoreload 1720 12516 Watching for file changes with StatReloader
ERROR 2024-03-22 15:17:08,492 basehttp 1720 9044 "GET / HTTP/1.1" 500 59
ERROR 2024-03-22 15:17:11,286 basehttp 1720 9044 "GET /favicon.ico HTTP/1.1" 500 59
INFO 2024-03-22 15:19:13,315 autoreload 1720 12516 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-22 15:19:15,546 autoreload 14428 14512 Watching for file changes with StatReloader
ERROR 2024-03-22 15:19:25,264 basehttp 14428 16292 "GET / HTTP/1.1" 500 59
ERROR 2024-03-22 15:19:26,415 basehttp 14428 16292 "GET /favicon.ico HTTP/1.1" 500 59
INFO 2024-03-22 15:22:20,352 autoreload 14428 14512 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-22 15:22:24,582 autoreload 13124 13544 Watching for file changes with StatReloader
INFO 2024-03-22 15:26:44,558 autoreload 13124 13544 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
INFO 2024-03-22 15:26:47,711 autoreload 5156 8476 Watching for file changes with StatReloader
INFO 2024-03-22 15:32:02,710 autoreload 5156 8476 C:\Users\lexip\PycharmProjects\GB\Flask\djangoProject\djangoProject\settings.py changed, reloading.
